title: <p align="center"> Kumar Gaurav </p>
logo: /assets/img/Gaurav's Pic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kumar-gaurav-81a9223b/">LinkedIn</a> |
  <a href="https://github.com/kumargauravb">GitHub</a>
  
  <br>   
  I'm working as an Automation Engineer on different technology stacks like C#, java, AWS.
  I am also responsible for functional and PACT testing.
  Working in FIS Global as Senior Lead Engineer.
  Working in payments domain for last 8 years.
  <br>
  </p>



theme: jekyll-theme-minimal
